apiVersion: v1
kind: Service
metadata:
  name: aks-journal
  namespace: aks-journal-app
  labels:
    app: aks-journal
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: aks-journal
---
apiVersion: v1
kind: Service
metadata:
  name: aks-journal-internal
  namespace: aks-journal-app
  labels:
    app: aks-journal
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: aks-journal
